apiVersion: v1
kind: Service
metadata:
  name: v01-process
spec:
  type: NodePort
  selector:
    app: v1-process
  ports:
    - name: v1-process
      protocol: TCP
      port: 80
      targetPort: 80
